app:
  name: api-gateway
  log_level: info

server:
  http_port: 8080

services:
  user:
    grpc_addr: user-service:50051
  task:
    grpc_addr: task-service:50051
  activity:
    grpc_addr: activity-service:50051

redis:
  host: redis
  port: 6379
  password: ""
  db: 0
  cache_ttl: 300

user_db:
  host: postgres-user
  port: 5432
  username: admin
  password: admin
  name: user_db
  ssl_mode: disable

task_db:
  host: postgres-task
  port: 5432
  username: admin
  password: admin
  name: task_db
  ssl_mode: disable

activity_db:
  enabled: true
  bucket_count: 100  
  shard_count: 2
  shards:
    - host: postgres-activity-shard-0
      port: 5432
      username: admin
      password: admin
      name: activity_db_shard_0
      ssl_mode: disable
    - host: postgres-activity-shard-1
      port: 5432
      username: admin
      password: admin
      name: activity_db_shard_1
      ssl_mode: disable


kafka:
  brokers:
    - kafka:9094
  topics:
    user_created: user.created
    user_updated: user.updated
    team_updated: team.updated
    task_created: task.created
    task_updated: task.updated
