app:
  name: user-service
  log_level: info

server:
  grpc_port: 50051
  http_port: 8080

database:
  host: postgres-user
  port: 5432
  username: admin
  password: admin
  name: user_db
  ssl_mode: disable

kafka:
  brokers:
    - kafka:9094
  topics:
    user_created: user.created
    user_updated: user.updated
    team_updated: team.updated

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

